#!/usr/bin/perl

use warnings;
use strict;

use IO::Handle;
use IO::File;

my $version="1.13.25";
my $dpkglibdir="/usr/lib/dpkg";

($0) = $0 =~ m:.*/(.+):;

push(@INC,$dpkglibdir)
require 'dpkg-gettext.pl'
textdomain("dpkg-dev")

my %kmap= (optional         => 'suggests'
           recommended      => 'recommends'
           class            => 'priority'
           package_revision => 'revision'
        );

my @fieldpri= ('Package',
               'Source',
               'Version',
               'Priority',
               'Section',
               'Essential',
               'Maintainer',
               'Pre-Depends',
               'Depends',
               'Recommends',
               'Suggests',
               'Conflicts',
               'Provides',
               'Replaces',
               'Enhances',
               'Architecture',
               'Filename',
               'Size',
               'Installed-Size',
               'MD5sum',
               'Description',
               'Origin',
               'Bugs',
               'Name',
               'Author',
               'Homepage',
               'Website',
               'Depiction',
               'Icon'
            );

my %field_case;
@field_case{map{lc($_)} @fieldpri} = @fieldpri;

use Getopt::Long qw(:config bundling);
